"""Convert the Roboflow basketball court-keypoint dataset (COCO) to YOLO-pose.

Ultralytics YOLO-pose wants one label .txt per image:

    cls  cx cy w h  px1 py1 v1  px2 py2 v2  ...  pxK pyK vK

with every coordinate normalized by image width/height and visibility v in
{0 absent, 1 labeled-hidden, 2 visible}. The Roboflow export is COCO with
absolute pixels, so we normalize and restructure into the images/ + labels/
layout ultralytics expects, and emit a data YAML.

The 33-point court schema has no published real-world template and no known
left-right mirror map, so `flip_idx` is the identity and training must set
`fliplr=0` (a horizontal flip would scramble the point identities). See
ADR-003/004 in docs/decisions.md.

    uv run python scripts/convert_court_coco_to_yolo_pose.py \
        --coco-root data/basketball-court-detection-2-13 --out data/court_pose
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

COCO_SPLITS = {"train": "train", "valid": "val", "test": "test"}


def convert_split(coco_root: Path, out: Path, coco_split: str, yolo_split: str) -> tuple[int, int]:
    ann_file = coco_root / coco_split / "_annotations.coco.json"
    data = json.loads(ann_file.read_text())
    images = {im["id"]: im for im in data["images"]}
    court_cat = next(c for c in data["categories"] if c.get("keypoints"))
    num_kpts = len(court_cat["keypoints"])

    by_image: dict[int, list[dict]] = {}
    for a in data["annotations"]:
        if a["category_id"] == court_cat["id"]:
            by_image.setdefault(a["image_id"], []).append(a)

    img_dir = out / "images" / yolo_split
    lbl_dir = out / "labels" / yolo_split
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for image_id, im in images.items():
        w, h = im["width"], im["height"]
        src = coco_root / coco_split / im["file_name"]
        link = img_dir / im["file_name"]
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(src.resolve())

        lines = []
        for a in by_image.get(image_id, []):
            bx, by, bw, bh = a["bbox"]
            cx, cy = (bx + bw / 2) / w, (by + bh / 2) / h
            nw, nh = bw / w, bh / h
            kp = a["keypoints"]
            parts = [f"0 {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}"]
            for i in range(num_kpts):
                px, py, v = kp[3 * i], kp[3 * i + 1], int(kp[3 * i + 2])
                if v == 0:
                    parts.append("0.000000 0.000000 0")
                else:
                    parts.append(f"{px / w:.6f} {py / h:.6f} {v}")
            lines.append(" ".join(parts))
        (lbl_dir / f"{Path(im['file_name']).stem}.txt").write_text("\n".join(lines) + "\n")
        written += 1
    return written, num_kpts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coco-root", default="data/basketball-court-detection-2-13")
    parser.add_argument("--out", default="data/court_pose")
    args = parser.parse_args()

    coco_root = Path(args.coco_root)
    out = Path(args.out)
    counts, num_kpts = {}, 0
    for coco_split, yolo_split in COCO_SPLITS.items():
        if not (coco_root / coco_split).exists():
            continue
        n, num_kpts = convert_split(coco_root, out, coco_split, yolo_split)
        counts[yolo_split] = n

    yaml = out / "court_pose.yaml"
    flip_idx = list(range(num_kpts))  # identity: no known L/R mirror → train fliplr=0
    yaml.write_text(
        f"# Auto-generated by scripts/convert_court_coco_to_yolo_pose.py\n"
        f"path: {out.resolve()}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"test: images/test\n"
        f"kpt_shape: [{num_kpts}, 3]\n"
        f"flip_idx: {flip_idx}\n"
        f"names:\n  0: court\n"
    )
    print(json.dumps({"images": counts, "num_keypoints": num_kpts, "yaml": str(yaml)}, indent=2))


if __name__ == "__main__":
    main()
